# Generated by Django 3.1.3 on 2020-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='/user_profile.png', upload_to='profile_pics'),
        ),
    ]
