# Generated by Django 3.1.3 on 2020-11-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201112_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='/user_profile.png', null=True, upload_to='profile_pics'),
        ),
    ]
